---
- name: Set reasonable keyboard behavior
  shell: defaults write -g InitialKeyRepeat -int 15
  when: ansible_facts['os_family'] == "Darwin"

- name: Set reasonable keyboard behavior
  shell: defaults write -g KeyRepeat -int 2
  when: ansible_facts['os_family'] == "Darwin"
