---
- name: Install audio-visual products
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    accept_external_apps: True
  with_items:
  - decimator
  - imagingedge   
  - atem
  when: ansible_facts['os_family'] == "Darwin"
